### ISSUE TITLE
python executable not found when installing on windows 8

### ISSUE THREAD

**Issue by barbalex** [garbados/spare#2]
Hi

Is spare supposed to work on windows 8?
When running `npm install -g spare` I get this error:
"Error: Can't find Python executable "python", you can set the PYTHON env variable"

Maybe I just have to do what the message says but I don't know how exactly to set this variable.

Alex

**Comment by barbalex** [comment]
I installed python 2.7.6 (after trying 3.3.5) and now I get this error:

MSBUILD : error MSB4132: Unbekannte Toolsversion 2.0. Verfügbare Toolsversionen sind "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\buil
d.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "
rebuild"
gyp ERR! cwd C:\Users\Alexander\AppData\Roaming\npm\node_modules\spare\node_modules\pouchdb\node_modules\level\node_modu
les\leveldown

(and more)

Alex

**Comment by garbados** [comment]
Huh! I've never tested Spare on Windows, but clearly it doesn't fair so well.

It looks like an error with [Leveldown](https://github.com/rvagg/node-leveldown). Maybe google around that?

**Comment by barbalex** [comment]
Yeah, seems like that was an issue.

According to Leveldown, node-gyp dependencies have to be checked. And node-gyp needs Microsoft Visual Studio C++ 2012 for Windows Desktop (Express works).

So I installed that and it seems that installing spare using `npm install -g spare` now worked. 

But when trying to backup I get this: 

```
PS C:\Users\Alexander\tmp> spare backup -r http://user:password@146.185.175.198:5984/artendb

path.js:204
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.<anonymous> (C:\Users\Alexander\AppData\Roaming\npm\node_modules\spare\lib\util.js:5:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by garbados** [comment]
Ah, aye, that points responsibility to spare's code. I'll check it out. Thanks!
